title: "client_side_logo_generator"
description: "A Client Side Logo Generator."
baseurl: "/client_side_logo_generator"
url: "https://europanite.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
highlighter: rouge